/** Textes de l'interface (français). Source partagée web + mobile. */

export const STRINGS = {
  app: {
    name: 'ReelVault',
    tagline: 'Ta bibliothèque de réels, organisée automatiquement.',
  },
  nav: {
    home: 'Accueil',
    library: 'Bibliothèque',
    dashboard: 'Tableau de bord',
    stats: 'Statistiques',
    digest: 'Ma sélection',
    categories: 'Catégories',
    settings: 'Paramètres',
    add: 'Ajouter un réel',
    addShort: 'Ajouter',
    search: 'Rechercher…',
    logout: 'Se déconnecter',
  },
  auth: {
    loginTitle: 'Connexion',
    signupTitle: 'Créer un compte',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    login: 'Se connecter',
    signup: "S'inscrire",
    noAccount: 'Pas encore de compte ?',
    hasAccount: 'Déjà un compte ?',
    loginError: 'E-mail ou mot de passe incorrect.',
    signupSuccess: 'Compte créé ! Vérifie tes e-mails pour confirmer.',
  },
  home: {
    title: 'Accueil',
    greeting: 'Bonjour',
    heroTitle: 'Ta bibliothèque de réels, organisée toute seule',
    heroSubtitle: 'Partage un réel vers ton compte connecté ou colle un lien : l\'IA s\'occupe du classement.',
    statReels: 'Réels',
    statCategories: 'Catégories',
    statAuthors: 'Comptes',
    featuredCategories: 'Catégories',
    recent: 'Récemment ajoutés',
    seeAll: 'Tout voir',
    emptyTitle: 'Rien pour l\'instant',
    emptySubtitle: 'Ajoute ton premier réel pour démarrer ta bibliothèque.',
  },
  library: {
    title: 'Ma bibliothèque',
    searchPlaceholder: 'Rechercher un réel, un compte, un mot-clé…',
    allCategories: 'Toutes les catégories',
    filterByAuthor: 'Filtrer par compte',
    filterByDate: 'Filtrer par date',
    sortRecent: 'Plus récents',
    sortOldest: 'Plus anciens',
    sortMostViewed: 'Plus consultés',
    addedOn: 'Ajouté le',
    by: 'par',
    views: 'vues',
    openInInstagram: 'Ouvrir dans Instagram',
    empty: {
      title: 'Ta bibliothèque est vide',
      subtitle: 'Ajoute ton premier réel en collant un lien, ou partage-en un depuis Instagram.',
      cta: 'Ajouter un réel',
    },
    emptyFiltered: {
      title: 'Aucun réel trouvé',
      subtitle: 'Essaie de modifier ta recherche ou tes filtres.',
    },
  },
  add: {
    title: 'Ajouter un réel',
    pasteLabel: 'Colle le lien du réel Instagram',
    placeholder: 'https://www.instagram.com/reel/…',
    submit: 'Ajouter à ma bibliothèque',
    invalid: 'Ce lien ne ressemble pas à un réel Instagram.',
    adding: 'Ajout en cours…',
    success: 'Réel ajouté ! Classement par l\'IA en cours.',
    duplicate: 'Ce réel est déjà dans ta bibliothèque.',
  },
  categories: {
    title: 'Mes catégories',
    rename: 'Renommer',
    merge: 'Fusionner',
    delete: 'Supprimer',
    create: 'Nouvelle catégorie',
    mergeInto: 'Fusionner dans…',
    deleteConfirm: 'Supprimer cette catégorie ? Les réels seront déclassés (sans catégorie).',
    reelCount: (n: number) => `${n} réel${n > 1 ? 's' : ''}`,
  },
  stats: {
    title: 'Statistiques',
    totalReels: 'Réels sauvegardés',
    byCategory: 'Répartition par catégorie',
    mostViewed: 'Les plus consultés',
    topAuthors: 'Comptes les plus sauvegardés',
    overTime: 'Évolution dans le temps',
    noData: 'Pas encore assez de données pour afficher des statistiques.',
  },
  settings: {
    title: 'Paramètres',
    account: 'Compte',
    instagram: 'Connexion Instagram',
    preferences: 'Préférences',
    displayName: 'Nom affiché',
    notifications: 'Notifications push',
    notificationsHelp: 'Reçois une notification quand un nouveau réel est capturé et classé.',
    theme: 'Thème',
    darkMode: 'Mode sombre',
    export: 'Exporter ma bibliothèque',
    exportCsv: 'Exporter en CSV',
    exportPdf: 'Exporter en PDF',
    deleteAccount: 'Supprimer mon compte',
    deleteAccountTitle: 'Zone de danger',
    deleteAccountDesc: 'Ces actions sont irréversibles. Procède avec prudence.',
    deleteAccountCta: 'Supprimer définitivement',
    deleteAccountWarning:
      'Cette action est permanente et irréversible. Les données suivantes seront supprimées :',
    deleteAccountList: [
      'Ton compte et tes identifiants de connexion',
      'Tous tes réels sauvegardés et leurs métadonnées',
      'Tes catégories et préférences',
      'Ta connexion Instagram',
      'Tes clés API',
      'Ton profil Second Brain et tes digests',
    ],
    deleteConfirmHint: 'Tape SUPPRIMER pour confirmer',
    deleteConfirmWord: 'SUPPRIMER',
    cancel: 'Annuler',
    save: 'Enregistrer',
    saved: 'Modifications enregistrées.',
    digestTitle: 'Sélection personnalisée',
    digestFrequencyLabel: 'Fréquence de ta sélection IA',
    digestFrequencySaved: 'Fréquence mise à jour.',
    profileTitle: 'Mon profil Second Brain',
    profileSubtitle: 'Ces réponses personnalisent ta sélection IA. Tu peux les modifier à tout moment.',
    profileSaved: 'Profil enregistré.',
  },
  apiKeys: {
    title: 'Mes clés API',
    intro:
      'Ajoute tes propres clés pour le classement IA (Gemini) et l\'enrichissement (RapidAPI). Tu peux en mettre plusieurs : ReelVault bascule automatiquement sur la suivante quand l\'une atteint son quota.',
    gemini: 'Gemini (classement IA)',
    geminiHelp: 'Clé Google AI Studio — https://aistudio.google.com → « Get API key ».',
    rapidapi: 'RapidAPI (enrichissement)',
    rapidapiHelp: 'Clé RapidAPI pour l\'API instagram120 (miniatures, légendes, auteurs).',
    placeholder: 'Colle ta clé ici',
    add: 'Ajouter',
    added: 'Clé ajoutée.',
    deleted: 'Clé supprimée.',
    none: 'Aucune clé. La clé partagée par défaut est utilisée (quota limité).',
    inCooldown: 'En pause (quota atteint)',
    lastError: 'Dernière erreur',
    deleteConfirm: 'Supprimer cette clé ?',
  },
  instagram: {
    title: 'Connecter mon compte Instagram',
    statusPending: 'Non connecté',
    statusActive: 'Connecté',
    statusRevoked: 'Déconnecté',
    intro: 'Connecte ton compte Instagram secondaire pour capturer automatiquement les réels que tu y partages.',
    connect: 'Se connecter avec Instagram',
    connecting: 'Redirection vers Instagram…',
    disconnect: 'Déconnecter',
    disconnecting: 'Déconnexion…',
    connectedAs: 'Connecté en tant que',
    connectSuccess: 'Compte Instagram connecté !',
    disconnectSuccess: 'Compte Instagram déconnecté.',
    errorDenied: 'Connexion annulée. Réessaie quand tu veux.',
    errorState: 'Session de connexion expirée. Réessaie.',
    errorExchange: 'Impossible de finaliser la connexion Instagram. Réessaie.',
    errorConfig: 'La connexion Instagram n\'est pas encore configurée côté serveur.',
  },
  pairing: {
    title: 'Relier ton compte principal',
    intro:
      'Pour ne capturer QUE les réels que TU partages (et ignorer les autres messages), relie ton compte principal une seule fois.',
    codeLabel: 'Ton code de jumelage',
    copy: 'Copier le code',
    copied: 'Code copié !',
    steps: (igUsername: string | null) => [
      'Ouvre Instagram sur ton COMPTE PRINCIPAL (celui depuis lequel tu partages des réels).',
      `Envoie ce code en message privé (DM) à ton compte connecté${igUsername ? ` @${igUsername}` : ''}.`,
      'Reviens ici : ton compte principal sera reconnu automatiquement.',
    ],
    paired: 'Compte principal relié',
    pairedHelp: 'Seuls les réels partagés depuis ce compte seront ajoutés à ta bibliothèque.',
    notPaired: 'Compte principal non relié',
    waiting: 'En attente du code envoyé depuis ton compte principal…',
    refresh: 'Vérifier',
  },
  onboarding: {
    skip: 'Passer',
    next: 'Continuer',
    back: 'Retour',
    finish: 'Terminer',
    step: 'Étape',
    of: 'sur',
    welcome: {
      title: 'Bienvenue sur ReelVault 👋',
      subtitle: 'En 3 étapes, on prépare ta bibliothèque de réels organisée automatiquement par l\'IA.',
      cta: 'C\'est parti',
    },
    connect: {
      title: 'Connecte ton compte Instagram',
      subtitle: 'Relie ton compte Instagram secondaire pour capturer automatiquement les réels que tu y partages. Tu peux aussi le faire plus tard dans les Paramètres.',
      connected: 'Compte connecté 🎉',
    },
    pair: {
      title: 'Relie ton compte principal',
      subtitle:
        'Pour ne capturer QUE les réels que TOI tu partages, envoie ce code une fois depuis ton compte principal.',
      needConnect: 'Connecte d\'abord ton compte Instagram à l\'étape précédente.',
    },
    keys: {
      title: 'Tes clés (IA & enrichissement)',
      subtitle:
        'ReelVault classe et enrichit tes réels grâce à 2 services gratuits. Ajoute tes clés — tu peux en mettre plusieurs (rotation automatique quand un quota est atteint).',
      optional:
        'Optionnel : sans clé perso, une clé partagée à quota limité est utilisée. Pour un usage confortable, mets les tiennes.',
      geminiTitle: 'Clé Gemini — classement par IA (gratuit)',
      geminiSteps: [
        'Va sur aistudio.google.com et connecte-toi avec un compte Google.',
        'Clique sur « Get API key » (ou « Obtenir une clé API »), en haut à gauche.',
        'Clique « Create API key » → choisis/crée un projet : une clé qui commence par « AIza… » apparaît.',
        'Copie-la et colle-la dans le champ Gemini ci-dessous. (Tu peux créer plusieurs clés pour la rotation.)',
      ],
      rapidTitle: 'Clé RapidAPI — miniatures, légendes & auteurs (gratuit)',
      rapidSteps: [
        'Crée un compte gratuit sur rapidapi.com.',
        'Ouvre l\'API « instagram120 » (rapidapi.com → recherche « instagram120 ») et clique « Subscribe » → plan « Basic » (gratuit).',
        'Dans l\'onglet « Endpoints », repère le header « X-RapidAPI-Key » et copie sa valeur (se termine par « …msh… »).',
        'Colle-la dans le champ RapidAPI ci-dessous.',
      ],
    },
    howto: {
      title: 'Comment ça marche',
      subtitle: 'Partage un réel vers ton compte connecté, ou colle un lien manuellement.',
      point1: 'Partage un réel depuis Instagram vers ton compte connecté — il atterrit ici tout seul.',
      point2: 'L\'IA le classe automatiquement dans la bonne catégorie.',
      point3: 'Retrouve, filtre et exporte toute ta bibliothèque quand tu veux.',
    },
    goals: {
      title: 'Pourquoi tu sauvegardes des réels ?',
      subtitle: 'Sélectionne tout ce qui te correspond (plusieurs choix possibles).',
      options: [
        { id: 'inspire',   label: 'M\'inspirer pour créer du contenu' },
        { id: 'learn',     label: 'Apprendre de nouvelles choses' },
        { id: 'ideas',     label: 'Garder des idées pour plus tard' },
        { id: 'watch',     label: 'Faire de la veille professionnelle' },
        { id: 'share',     label: 'Partager avec d\'autres personnes' },
        { id: 'entertain', label: 'Me divertir' },
      ],
    },
    interests: {
      title: 'Quels sujets t\'intéressent ?',
      subtitle: 'Sélectionne tes centres d\'intérêt — cela affine ta sélection personnalisée.',
      options: [
        'Fitness & Sport',
        'Cuisine & Food',
        'Tech & IA',
        'Mode & Style',
        'Beauté & Skincare',
        'Voyage & Aventure',
        'Business & Marketing',
        'Art & Design',
        'Musique',
        'Photo & Vidéo',
        'Développement perso',
        'Nature & Outdoor',
        'Architecture & Déco',
        'Finance & Crypto',
        'Humour & Divertissement',
        'Bien-être & Santé',
        'Gaming',
        'Science',
        'DIY & Craft',
        'Famille & Parentalité',
        'Animaux',
        'Entrepreneuriat',
        'Danse',
        'Lecture & Littérature',
        'Mode de vie durable',
        'Relations & Psychologie',
        'Langues & Culture',
        'Spiritualité & Philosophie',
      ],
    },
    persona: {
      title: 'Qui es-tu ?',
      subtitle: 'Pour mieux personnaliser ta sélection.',
      personaOptions: [
        { id: 'creator',  label: 'Créateur·trice de contenu' },
        { id: 'pro',      label: 'Professionnel·le' },
        { id: 'student',  label: 'Étudiant·e' },
        { id: 'curious',  label: 'Curieux·se passionné·e' },
        { id: 'other',    label: 'Autre' },
      ],
      expertiseLabel: 'Ton niveau général',
      expertiseOptions: [
        { id: 'debutant',      label: 'Débutant·e' },
        { id: 'intermediaire', label: 'Intermédiaire' },
        { id: 'avance',        label: 'Expert·e' },
      ],
      timeLabel: 'Temps disponible / semaine pour explorer des contenus',
      timeOptions: [
        { id: 'light',  label: '< 2h — je survole' },
        { id: 'medium', label: '2-5h — régulier·e' },
        { id: 'heavy',  label: '5h+ — j\'explore en profondeur' },
      ],
    },
    about: {
      title: 'Dis-nous-en plus (optionnel)',
      subtitle: 'Quelques mots sur ce que tu cherches vraiment — l\'IA s\'en souviendra pour ta sélection.',
      placeholder: 'Ex : Je cherche surtout des idées pour mon business de coaching, des techniques de montage vidéo, et des tendances mode streetwear…',
    },
    frequency: {
      title: 'À quelle fréquence veux-tu ta sélection ?',
      subtitle: 'Chaque semaine ou chaque mois, l\'IA choisit les meilleurs réels que tu as sauvegardés, selon ton profil.',
      weekly: {
        label: 'Hebdomadaire',
        desc: 'Chaque lundi, les tops de la semaine.',
      },
      monthly: {
        label: 'Mensuel',
        desc: 'Chaque 1er du mois, les pépites du mois.',
      },
      off: {
        label: 'Non merci',
        desc: 'Tu pourras activer ça dans les réglages.',
      },
    },
    done: {
      title: 'Tout est prêt ✅',
      subtitle: 'Ta bibliothèque t\'attend. Ajoute ton premier réel dès maintenant.',
      cta: 'Accéder à ma bibliothèque',
    },
  },
  digest: {
    title: 'Ma sélection',
    empty: 'Aucune sélection pour l\'instant. Il faut au moins 3 réels dans ta bibliothèque sur la période, et que ta fréquence soit activée.',
    summaryTitle: 'Synthèse IA',
    selectionTitle: 'Les réels sélectionnés',
    rateTitle: 'Cette sélection était pertinente ?',
    rateHelp: 'Ta note aide l\'IA à mieux te connaître.',
    rated: 'Tu as noté cette sélection',
    thanks: 'Merci pour ta note !',
    generateNow: 'Générer maintenant',
    generating: 'Génération en cours…',
    history: 'Historique des sélections',
    periodLabel: (start: string, end: string) => `Du ${start} au ${end}`,
    frequencyLabel: (f: string) => f === 'weekly' ? 'Hebdomadaire' : f === 'monthly' ? 'Mensuel' : '—',
    stars: (n: number) => `${n} étoile${n > 1 ? 's' : ''}`,
    noHistory: 'Pas encore d\'historique.',
    tooFewReels: 'Pas assez de réels sur la période pour générer une sélection (minimum 3).',
    generateError: 'Impossible de générer la sélection. Réessaie plus tard.',
    period: {
      weekly: 'Sélection hebdomadaire',
      monthly: 'Sélection mensuelle',
    },
  },
  common: {
    loading: 'Chargement…',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    close: 'Fermer',
    retry: 'Réessayer',
    error: 'Une erreur est survenue. Réessaie.',
    yes: 'Oui',
    no: 'Non',
  },
  notifications: {
    newReelTitle: 'Nouveau réel sauvegardé 🎬',
    newReelBody: (category: string) => `Un réel a été classé dans « ${category} ».`,
    digestTitle: 'Ta sélection est prête ✨',
    digestBody: (n: number) => `${n} réel${n > 1 ? 's' : ''} sélectionné${n > 1 ? 's' : ''} pour toi cette semaine.`,
  },
} as const;

export type Strings = typeof STRINGS;
