/** Textes de l'interface (français). Source partagée web + mobile. */

export const STRINGS = {
  app: {
    name: 'ReelVault',
    tagline: 'Ta bibliothèque de réels, organisée automatiquement.',
  },
  nav: {
    library: 'Bibliothèque',
    dashboard: 'Tableau de bord',
    stats: 'Statistiques',
    settings: 'Paramètres',
    add: 'Ajouter un réel',
    logout: 'Se déconnecter',
  },
  auth: {
    loginTitle: 'Connexion',
    signupTitle: 'Créer un compte',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    login: 'Se connecter',
    signup: "S'inscrire",
    noAccount: 'Pas encore de compte ?',
    hasAccount: 'Déjà un compte ?',
    loginError: 'E-mail ou mot de passe incorrect.',
    signupSuccess: 'Compte créé ! Vérifie tes e-mails pour confirmer.',
  },
  library: {
    title: 'Ma bibliothèque',
    searchPlaceholder: 'Rechercher un réel, un compte, un mot-clé…',
    allCategories: 'Toutes les catégories',
    filterByAuthor: 'Filtrer par compte',
    filterByDate: 'Filtrer par date',
    sortRecent: 'Plus récents',
    sortOldest: 'Plus anciens',
    sortMostViewed: 'Plus consultés',
    addedOn: 'Ajouté le',
    by: 'par',
    views: 'vues',
    openInInstagram: 'Ouvrir dans Instagram',
    empty: {
      title: 'Ta bibliothèque est vide',
      subtitle: 'Ajoute ton premier réel en collant un lien, ou partage-en un depuis Instagram.',
      cta: 'Ajouter un réel',
    },
    emptyFiltered: {
      title: 'Aucun réel trouvé',
      subtitle: 'Essaie de modifier ta recherche ou tes filtres.',
    },
  },
  add: {
    title: 'Ajouter un réel',
    pasteLabel: 'Colle le lien du réel Instagram',
    placeholder: 'https://www.instagram.com/reel/…',
    submit: 'Ajouter à ma bibliothèque',
    invalid: 'Ce lien ne ressemble pas à un réel Instagram.',
    adding: 'Ajout en cours…',
    success: 'Réel ajouté ! Classement par l\'IA en cours.',
    duplicate: 'Ce réel est déjà dans ta bibliothèque.',
  },
  categories: {
    title: 'Mes catégories',
    rename: 'Renommer',
    merge: 'Fusionner',
    delete: 'Supprimer',
    create: 'Nouvelle catégorie',
    mergeInto: 'Fusionner dans…',
    deleteConfirm: 'Supprimer cette catégorie ? Les réels seront déclassés (sans catégorie).',
    reelCount: (n: number) => `${n} réel${n > 1 ? 's' : ''}`,
  },
  stats: {
    title: 'Statistiques',
    totalReels: 'Réels sauvegardés',
    byCategory: 'Répartition par catégorie',
    mostViewed: 'Les plus consultés',
    topAuthors: 'Comptes les plus sauvegardés',
    overTime: 'Évolution dans le temps',
    noData: 'Pas encore assez de données pour afficher des statistiques.',
  },
  settings: {
    title: 'Paramètres',
    account: 'Compte',
    instagram: 'Connexion Instagram',
    preferences: 'Préférences',
    displayName: 'Nom affiché',
    notifications: 'Notifications push',
    notificationsHelp: 'Reçois une notification quand un nouveau réel est capturé et classé.',
    theme: 'Thème',
    darkMode: 'Mode sombre',
    export: 'Exporter ma bibliothèque',
    exportCsv: 'Exporter en CSV',
    exportPdf: 'Exporter en PDF',
    deleteAccount: 'Supprimer mon compte',
    save: 'Enregistrer',
    saved: 'Modifications enregistrées.',
  },
  instagram: {
    title: 'Connecter mon compte Instagram',
    statusPending: 'Non connecté',
    statusActive: 'Connecté',
    statusRevoked: 'Déconnecté',
    intro: 'Connecte ton compte Instagram secondaire pour capturer automatiquement les réels que tu y partages.',
    connect: 'Se connecter avec Instagram',
    connecting: 'Redirection vers Instagram…',
    disconnect: 'Déconnecter',
    disconnecting: 'Déconnexion…',
    connectedAs: 'Connecté en tant que',
    connectSuccess: 'Compte Instagram connecté !',
    disconnectSuccess: 'Compte Instagram déconnecté.',
    errorDenied: 'Connexion annulée. Réessaie quand tu veux.',
    errorState: 'Session de connexion expirée. Réessaie.',
    errorExchange: 'Impossible de finaliser la connexion Instagram. Réessaie.',
    errorConfig: 'La connexion Instagram n\'est pas encore configurée côté serveur.',
  },
  onboarding: {
    skip: 'Passer',
    next: 'Continuer',
    back: 'Retour',
    finish: 'Terminer',
    step: 'Étape',
    of: 'sur',
    welcome: {
      title: 'Bienvenue sur ReelVault 👋',
      subtitle: 'En 3 étapes, on prépare ta bibliothèque de réels organisée automatiquement par l\'IA.',
      cta: 'C\'est parti',
    },
    connect: {
      title: 'Connecte ton compte Instagram',
      subtitle: 'Relie ton compte Instagram secondaire pour capturer automatiquement les réels que tu y partages. Tu peux aussi le faire plus tard dans les Paramètres.',
      connected: 'Compte connecté 🎉',
    },
    howto: {
      title: 'Comment ça marche',
      subtitle: 'Partage un réel vers ton compte connecté, ou colle un lien manuellement.',
      point1: 'Partage un réel depuis Instagram vers ton compte connecté — il atterrit ici tout seul.',
      point2: 'L\'IA le classe automatiquement dans la bonne catégorie.',
      point3: 'Retrouve, filtre et exporte toute ta bibliothèque quand tu veux.',
    },
    done: {
      title: 'Tout est prêt ✅',
      subtitle: 'Ta bibliothèque t\'attend. Ajoute ton premier réel dès maintenant.',
      cta: 'Accéder à ma bibliothèque',
    },
  },
  common: {
    loading: 'Chargement…',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    close: 'Fermer',
    retry: 'Réessayer',
    error: 'Une erreur est survenue. Réessaie.',
    yes: 'Oui',
    no: 'Non',
  },
  notifications: {
    newReelTitle: 'Nouveau réel sauvegardé 🎬',
    newReelBody: (category: string) => `Un réel a été classé dans « ${category} ».`,
  },
} as const;

export type Strings = typeof STRINGS;
